{
 "title": "Jenkins",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up time Jenkins",
   "type": "timeseries",
   "description": "Aqui podemos acompanhar o tempo em que o Jenkins ficou operante sem interferências ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "default_jenkins_uptime\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de CPU -  Representa o percentual de tempo que a CPU",
   "type": "timeseries",
   "description": "O uso de CPU mede quanto da capacidade da CPU está sendo utilizada em um dado momento. Ele é uma métrica fundamental para avaliar o quão \"ocupada\" a CPU está em termos de execução de processos.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"jenkins\", instance=\"172.17.0.2:8080\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumo de memoria",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"jenkins\", instance=\"172.17.0.2:8080\", area=\"heap\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de Requisições HTTP",
   "type": "gauge",
   "description": "somando todas as métricas de http_requests para o job Jenkins e exibir uma única série.\n\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_count{job=\"jenkins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Respostas HTTP com erro",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_serverError_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carga de uso de CPU Carga de uso (Load Average)",
   "type": "timeseries",
   "description": "A carga de uso (também chamada de load average) refere-se ao número médio de processos que estão na fila esperando para serem executados em um determinado período de tempo. Essa métrica é mais abrangente e reflete a demanda de processamento no sistema, não apenas o uso ativo da CPU.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "system_cpu_load", "legendFormat": "__auto" }
   ]
  }
 ]
}